# By   Super_chen520
# Date 2023-8-30

name: Chemdah Release

on:
  push:
    branches: [ "rebirth" ]
  pull_request:
    branches: [ "rebirth" ]

jobs:
  releaseJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build

      # First build
      - name: build
        id: build_1
        run: ./gradlew build
      # Second build
      - name: build (retry 1)
        id: build_2
        if: steps.build_1.outcome == 'failure'
        run: ./gradlew build
       # Third build
      - name: build (retry 2)
        id: build_3
        if: steps.build_2.outcome == 'failure'
        run: ./gradlew build
       # Fourth build
      - name: build (retry 3)
        id: build_4
        if: steps.build_3.outcome == 'failure'
        run: ./gradlew build

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/libs/*.jar"
          body: |
            Commit ${{ steps.short_sha.outputs.sha_short }}
            This release is automatically compiled by GitHub Actions
          name: Chemdah Automation Compile ${{ steps.short_sha.outputs.sha_short }}
          draft: false
          tag_name: commit-${{ steps.short_sha.outputs.sha_short }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_KEY }}
          GITHUB_REPOSITORY: LangZongz/Chemdah
